### ISSUE TITLE
Add project cards

### ISSUE THREAD

**Issue by pexeixv** [hannesxc/personal-portfolio#2]
The projects page is completely empty. I will create dummy project cards that you can replace with your real projects once you have some. 
If you feel this a valid issue, assign it to me and I will work on it under Hacktoberfest.

![image](https://user-images.githubusercontent.com/68476117/193461136-d102279f-bcfe-4389-8943-e8ba8c6bd25b.png)

**Comment by hannesxc** [comment]
Thank you, please feel free to do so.
